number: '0123456789٠١٢٣٤٥٦٧٨٩'
symbol: "!\"#'$%&()*+,-./:;<=>?@[\\]^_`{|}~ €؟،ـ:.\",’~><؛×÷‘|[]°"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzاأإآبتثجحخدذرزسشصضطظعغفقكلمنهوىيءئؤة'
experiment_name: 'base'
train_data: 'balancedData'
valid_data: 'balancedData/val'
print_logs: False
manualSeed: 1111
workers: 4
batch_size: 32 #32
num_iter: 1000
valInterval: 1000
saved_model: '' #'saved_models/en_filtered/iter_1000.pth'
FT: False
optim: False
lr: 1.4
beta1: 0.9
rho: 0.95
eps: 0.000000001
grad_clip: 5
#Data processing
select_data: 'train' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 300
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False